

greetings1: "Привет, я загадал число, попробуй его отгадать! "
greetings2: "Делай попытку, можно вводить числа от 0 до 1000!"
wrongAnswer1: "Мое число побольше твоего"
wrongAnswer2: "Мое число меньше твоего"
rightAnswer: "Ты угадал, я загадал число "

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    show-sql: true